name: update-deno-dependencies

on:
  schedule:
    - cron: "0 0 * * 6"

jobs:
  udd:
    strategy:
      matrix:
        runner:
          - ubuntu-latest
        version:
          - "1.x"
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: "${{ matrix.version }}"
      - name: Update dependencies
        run:
          deno run -A https://deno.land/x/udd/main.ts src/deps.ts test/deps.ts
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "chore(deps): update deno dependencies"
          title: Update Deno Dependencies
          body: >
            Automated updates by [deno-udd](https://github.com/hayd/deno-udd)
            and [create-pull-request](https://github.com/peter-evans/create-pull-request)
            GitHub action
          branch: update-deno-dependencies
          author: GitHub <noreply@github.com>
          delete-branch: true
